services:
  - type: web
    name: tsh-ar-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIALECT
        value: sqlite
